$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$entry = Join-Path $root 'ginkgo.css'
$modules = @('base', 'typography', 'layout', 'toc', 'outline', 'code',
    'front-matter', 'table', 'list', 'blockquote', 'math', 'tasklist',
    'sidebar', 'scrollbar', 'window', 'print')

$parts = @('/* Ginkgo — Typora Theme (银杏主题); generated by build-theme.ps1 */')
foreach ($module in $modules) {
    $path = Join-Path (Join-Path $root 'ginkgo') "$module.css"
    $css = Get-Content -LiteralPath $path -Raw -Encoding UTF8
    $parts += $css.TrimEnd()
}
[System.IO.File]::WriteAllText($entry, ($parts -join "`n`n") + "`n", [System.Text.UTF8Encoding]::new($false))
